#!/usr/bin/env python3
"""Generate an Android platform smoke test from the catalog.

The catalog claims, for thousands of symbols, which library provides them. A wrong
claim compiles fine and only shows up when a device tries to load the library. On
AArch64 the imports are GOT slots with R_AARCH64_GLOB_DAT relocations, which the
linker resolves eagerly, so a shared object that merely *declares* a few hundred
imports forces the device to resolve every one of them at load time: if any pair is
wrong, the load fails and the process dies instead of drawing.

The generated library therefore imports a sample from every platform library,
brings up EGL and clears the window to a distinctive colour. The colour on screen
means the whole sample resolved.

usage:
  python make_android_smoke.py --catalog <include/os/android> --abi arm64 --out smoke.asm
"""
from __future__ import annotations

import argparse
import tomllib
from pathlib import Path

ABI_BITS = {
    "aarch64": 0,
    "arm": 1,
    "i686": 2,
    "riscv64": 3,
    "x86_64": 4,
}
ABI_DIRS = {
    "aarch64": "arm64-v8a",
    "arm": "armeabi-v7a",
    "i686": "x86",
    "riscv64": "riscv64",
    "x86_64": "x86_64",
}

HEADER = """// Generated by make_android_smoke.py: a load-time check of the symbol catalog.
//
// Every symbol below is imported from the library the catalog names for it. The
// loader resolves all of them when this object is loaded, so a wrong library in
// the catalog turns into a failed load instead of a wrong picture.
import("format/format.inc");
import("os/android/imports.inc");
import("arm/a64-macros.inc");

let image: map = format_elf64_so_aarch64(
    "libmain.so",
    list.of(
        format_segment(".text", format_load | format_readable | format_executable),
        format_segment(".data", format_load | format_readable | format_writeable)
    )
)
let exports: list = format_elfso_export_new()
format_elfso_export_many_mut(exports, list.of("ANativeActivity_onCreate"), ".text", 16)
let imports: list = format_elfso_import_new()
"""

CODE = """
format_elfso_tables_mut(image, exports, imports)
format_begin(image);

format_segment_begin(image, ".text");

ANativeActivity_onCreate:
    b smoke_install_callbacks

smoke_install_callbacks:
    ldr x1, [x0]
    adrp x2, smoke_on_window_created
    add x2, x2, :lo12:smoke_on_window_created
    str x2, [x1, #56]
    ret

// onNativeWindowCreated(activity, window): clear the window to the smoke colour.
smoke_on_window_created:
    stp x19, x30, [sp, #-16]!
    sub sp, sp, #32
    mov x19, x1

    mov w0, #0
    ldr x8, eglGetDisplay
    blr x8
    adrp x9, g_display
    add x9, x9, :lo12:g_display
    str x0, [x9]

    mov x1, #0
    mov x2, #0
    ldr x8, eglInitialize
    blr x8

    ldr x0, g_display
    adrp x1, smoke_egl_config_attribs
    add x1, x1, :lo12:smoke_egl_config_attribs
    add x2, sp, #0
    mov w3, #1
    add x4, sp, #8
    ldr x8, eglChooseConfig
    blr x8

    ldr x0, g_display
    ldr x1, [sp, #0]
    mov x2, x19
    mov x3, #0
    ldr x8, eglCreateWindowSurface
    blr x8
    adrp x9, g_surface
    add x9, x9, :lo12:g_surface
    str x0, [x9]

    ldr x0, g_display
    ldr x1, [sp, #0]
    mov x2, #0
    adrp x3, smoke_egl_context_attribs
    add x3, x3, :lo12:smoke_egl_context_attribs
    ldr x8, eglCreateContext
    blr x8
    adrp x9, g_context
    add x9, x9, :lo12:g_context
    str x0, [x9]

    ldr x0, g_display
    ldr x1, g_surface
    mov x2, x1
    ldr x3, g_context
    ldr x8, eglMakeCurrent
    blr x8

    adrp x9, smoke_color
    add x9, x9, :lo12:smoke_color
    ldr s0, [x9, #0]
    ldr s1, [x9, #4]
    ldr s2, [x9, #8]
    ldr s3, [x9, #12]
    ldr x8, glClearColor
    blr x8

    mov w0, #0x4000
    ldr x8, glClear
    blr x8

    ldr x0, g_display
    ldr x1, g_surface
    ldr x8, eglSwapBuffers
    blr x8

    add sp, sp, #32
    ldp x19, x30, [sp], #16
    ret

format_segment_end(image, ".text");

format_segment_begin(image, ".data");
align(8);
g_display:
    dq(0)
g_surface:
    dq(0)
g_context:
    dq(0)

align(8);
// A colour nothing else in this repository uses, so a screenshot cannot be
// mistaken for the renderer example: 0.85, 0.1, 0.55, 1.0.
smoke_color:
    dd(0x3F59999A)
    dd(0x3DCCCCCD)
    dd(0x3F0CCCCD)
    dd(0x3F800000)

align(4);
smoke_egl_config_attribs:
    dd(0x3033)
    dd(0x0004)
    dd(0x3040)
    dd(0x0004)
    dd(0x3024)
    dd(8)
    dd(0x3023)
    dd(8)
    dd(0x3022)
    dd(8)
    dd(0x3038)
    dd(0)

smoke_egl_context_attribs:
    dd(0x3098)
    dd(2)
    dd(0x3038)
    dd(0)

format_segment_end(image, ".data");

format_finish(image);
"""


def load_aliases(catalog: Path) -> dict[str, str]:
    """Read library -> alias straight from the generated includes."""
    aliases: dict[str, str] = {}
    for path in sorted((catalog / "imports").glob("*.inc")):
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("const android_import_") and "_so: string" in line:
                alias = line.split("const android_import_", 1)[1].split("_so:", 1)[0]
                library = line.split('"')[1]
                aliases[library] = alias
                break
    return aliases


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--catalog", type=Path, required=True)
    parser.add_argument("--abi", choices=sorted(ABI_BITS), default="aarch64")
    parser.add_argument("--per-library", type=int, default=24)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--only-libraries", default="",
                        help="comma separated library names to restrict the sample to")
    parser.add_argument("--avoid", default="",
                        help="comma separated symbols to leave out, e.g. ones the device does not export")
    args = parser.parse_args()

    with (args.catalog / "catalog" / "symbols.toml").open("rb") as stream:
        data = tomllib.load(stream)
    bit = 1 << ABI_BITS[args.abi]
    aliases = load_aliases(args.catalog)
    only = {name.strip() for name in args.only_libraries.split(",") if name.strip()}
    avoid = {name.strip() for name in args.avoid.split(",") if name.strip()}

    per_library: dict[str, list[str]] = {}
    for symbol, row in data["symbols"].items():
        if not row["abis"] & bit:
            continue
        # An import slot is keyed by symbol name, so a symbol that several
        # libraries provide can only be imported from one of them. The smoke takes
        # the symbols that belong to exactly one library; the multi-library ones
        # are the caller's choice, which is what the catalog's library list is for.
        if "," in row["lib"]:
            continue
        if symbol in avoid:
            continue
        for entry in row["lib"].split(","):
            library = entry.rsplit(":", 1)[0]
            if library not in aliases:
                continue
            if only and library not in only:
                continue
            bucket = per_library.setdefault(library, [])
            if len(bucket) < args.per_library:
                bucket.append(symbol)

    lines = [HEADER]
    total = 0
    for library in sorted(per_library):
        symbols = per_library[library]
        alias = aliases[library]
        lines.append(f"// {library}: {len(symbols)} sampled symbols")
        lines.append(f"android_import_{alias}_add_slots_mut(imports, list.of(")
        lines.append(",\n".join(f"    android_import_{alias}_{symbol}" for symbol in symbols))
        lines.append("))")
        total += len(symbols)
    # The drawing code needs its own imports, and they are part of the check too.
    lines.append("android_import_egl_add_slots_mut(imports, list.of(")
    lines.append("    android_import_egl_eglGetDisplay, android_import_egl_eglInitialize,")
    lines.append("    android_import_egl_eglChooseConfig, android_import_egl_eglCreateWindowSurface,")
    lines.append("    android_import_egl_eglCreateContext, android_import_egl_eglMakeCurrent,")
    lines.append("    android_import_egl_eglSwapBuffers))")
    lines.append("android_import_glesv2_add_slots_mut(imports, list.of(")
    lines.append("    android_import_glesv2_glClearColor, android_import_glesv2_glClear))")
    lines.append(CODE)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{args.out}: {total} sampled symbols across {len(per_library)} libraries "
          f"for {args.abi} ({ABI_DIRS[args.abi]})")
    for library in sorted(per_library):
        print(f"  {library}: {len(per_library[library])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
