pub const data = @import("data/root.zig");
pub const frontend = @import("frontend/root.zig");

const std = @import("std");

pub const Module = frontend.Module;
pub const Target = frontend.Target;
pub const Isa = frontend.Isa;
pub const SourceSpan = frontend.SourceSpan;
pub const SourceId = frontend.SourceId;
pub const SourceInput = frontend.SourceInput;
pub const SourceMap = frontend.SourceMap;
pub const SourceLocation = frontend.SourceLocation;
pub const Value = frontend.Value;
pub const ValueType = frontend.ValueType;
pub const IntegerValue = frontend.IntegerValue;
pub const StructFieldValue = frontend.StructFieldValue;
pub const StructValue = frontend.StructValue;
pub const LowerError = frontend.LowerError;
pub const LowerOptions = frontend.LowerOptions;
pub const IncludeResolver = frontend.IncludeResolver;
pub const IncludeRequest = frontend.IncludeRequest;
pub const IncludeSource = frontend.IncludeSource;
pub const lowerSource = frontend.lowerSource;
pub const lowerSourceIntoModule = frontend.lowerSourceIntoModule;
pub const lowerSourceIntoModuleWithPath = frontend.lowerSourceIntoModuleWithPath;
pub const lowerSourceIntoModuleWithPathOptions = frontend.lowerSourceIntoModuleWithPathOptions;
pub const FragmentId = frontend.FragmentId;
pub const ModuleLayout = frontend.ModuleLayout;
pub const SectionLayout = frontend.SectionLayout;
pub const FragmentLayout = frontend.FragmentLayout;
pub const ListingOptions = frontend.ListingOptions;
pub const OutputImage = frontend.OutputImage;
pub const OutputKind = frontend.OutputKind;
pub const WriterResult = frontend.WriterResult;
pub const DeferredStatement = frontend.DeferredStatement;
pub const DeferredBlock = frontend.DeferredBlock;
pub const LateLayoutStatement = frontend.LateLayoutStatement;
pub const LateLayoutBlock = frontend.LateLayoutBlock;
pub const layoutModule = frontend.layoutModule;
pub const renderFlatListing = frontend.renderFlatListing;
pub const encodeInstructionFragments = frontend.encodeInstructionFragments;
pub const runLateLayoutPhase = frontend.runLateLayoutPhase;
pub const FixupId = frontend.FixupId;
pub const Fixup = frontend.Fixup;
pub const FixupPassResult = frontend.FixupPassResult;
pub const resolveFixups = frontend.resolveFixups;
pub const writeOutput = frontend.writeOutput;

test "frontend declarations are test-reachable" {
    std.testing.refAllDecls(data);
    std.testing.refAllDecls(data.config);
    std.testing.refAllDecls(frontend);
    std.testing.refAllDecls(frontend.ast);
    std.testing.refAllDecls(frontend.backend_adapter);
    std.testing.refAllDecls(frontend.diagnostic);
    std.testing.refAllDecls(frontend.expr);
    std.testing.refAllDecls(frontend.fixup);
    std.testing.refAllDecls(frontend.fragment);
    std.testing.refAllDecls(frontend.layout);
    std.testing.refAllDecls(frontend.lexer);
    std.testing.refAllDecls(frontend.lower);
    std.testing.refAllDecls(frontend.module);
    std.testing.refAllDecls(frontend.output);
    std.testing.refAllDecls(frontend.pass);
    std.testing.refAllDecls(frontend.parser);
    std.testing.refAllDecls(frontend.section);
    std.testing.refAllDecls(frontend.source);
    std.testing.refAllDecls(frontend.symbol);
    std.testing.refAllDecls(frontend.target);
    std.testing.refAllDecls(frontend.typecheck);
    std.testing.refAllDecls(frontend.types);
    std.testing.refAllDecls(frontend.value);
}
