"""Render batch E5 (FEAT_MOPS, FEAT_CSSC) into standalone XIRASM artifacts.

Independent companion to generate_a64.py. It reuses the finite-form signature and
field-expression model but emits a self-contained pair of include files instead
of merging into instructions.inc:

    a64/generated/instructions-e5.inc        -- a64_<mn>_word/_shape/emitter fns
    a64/generated/instructions-e5-macros.inc -- natural statement macros
    a64/generated/e5-manifest.json           -- pinned source/provenance manifest

CSSC macros parse through the shared a64_operands. Conflicting scalar CSSC
mnemonics are dispatched by the existing shared macro owner and retain cssc_*
compatibility aliases here. MOPS macros use a64_mops_operands with an explicit
syntax class so required brackets and writeback markers are validated.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

from e5_rules import CSSC_SCALAR_CONFLICTS
from generate_a64 import KINDS, signature
from source import canonical, digest, require

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
BATCH = "E5"


def validate_e5(data):
    require(data["format_version"] == 1 and data["batch"] == BATCH, "rules", "bad E5 header")
    require(data.get("blocked_records") == [] and not data.get("failures"), BATCH,
            "E5 has blocked or failed records")
    require(data.get("alternatives") and all(a["status"] == "converted"
                                            for a in data["alternatives"]),
            BATCH, "unaccounted translation alternative")
    planned = set(data["planned_records"])
    require({f["record_id"] for f in data["forms"]} == planned, BATCH, "source record missing")
    identities = set()
    for form in data["forms"]:
        require(form["id"] not in identities, "forms", "duplicate form id")
        identities.add(form["id"])
        word = form["base"]
        require(type(word) is int and 0 <= word <= 0xFFFFFFFF, form["id"], "invalid base word")
        require(word & form["fixed_mask"] == form["fixed_value"], form["id"],
                "source fixed bits changed")
        require(word & form["should_be_mask"] == form["should_be_value"], form["id"],
                "noncanonical preferred bits")
        overlap = 0
        for operand in form["operands"]:
            require("transform" not in operand and "list" not in operand, form["id"],
                    "obsolete operand mapping")
            require(operand["kind"] in KINDS, form["id"], "invalid operand kind")
        for field in form["fields"]:
            index, width, offset = field["operand"], field["width"], field["lsb"]
            require(0 <= index < len(form["operands"]) and 0 < width <= 26
                    and 0 <= offset <= 32 - width, form["id"], "invalid dynamic field")
            bits = ((1 << width) - 1) << offset
            require(not bits & (overlap | word | form["fixed_mask"] | form["should_be_mask"]),
                    form["id"], "overlapping field")
            overlap |= bits
        for constraint in form.get("constraints", []):
            require(constraint["kind"] == "distinct", form["id"], "unsupported E5 constraint")
            require(0 <= constraint["left"] < len(form["operands"])
                    and 0 <= constraint["right"] < len(form["operands"]),
                    form["id"], "invalid E5 constraint operand")
        signature(form["operands"])


def value_expr(form, field):
    value = f"p{field['operand']}"
    transform = field.get("transform")
    if transform:
        kind = transform["kind"]
        if kind == "subone":
            value = f"({1 << transform['width']} - {value})"
        elif kind == "slice":
            value = f"({value} >> {transform['shift']})"
        elif kind == "lookup":
            value = f"a64_option_index({value}, list.of({', '.join(map(str, transform['values']))}))"
        elif kind == "xor":
            value = f"({value} ^ {transform['value']})"
        elif kind == "bias":
            value = f"({value} - {transform['value']})"
        elif kind == "negate":
            value = f"(-{value})"
        elif kind == "complement":
            value = f"(~{value})"
        else:
            raise ValueError(f"E5 uses no {kind} field transform")
        if kind not in {"slice", "subone", "lookup"} and transform.get("shift"):
            value = f"({value} >> {transform['shift']})"
    return f"({value} & {(1 << field['width']) - 1})"


def render_word_functions(groups):
    code = ["// Generated by tools/arm64/generate_a64_e5.py. See e5-manifest.json and NOTICE.",
            "// FEAT_MOPS and FEAT_CSSC finite forms; kept separate from instructions.inc.",
            "// All word functions use the a64_e5_ prefix to avoid DuplicateMetaFunction",
            "// with the existing B1-B4/E1-E4 encoders in instructions.inc.", ""]
    for mnemonic, forms in sorted(groups.items()):
        code.append(f"fn a64_e5_{mnemonic}_word(args: list) -> u64 {{")
        code += ["    const flat: list = a64_flatten(args)",
                 "    const key: u64 = a64_signature(flat)"]
        by_key = defaultdict(list)
        for form in forms:
            by_key[signature(form["operands"])].append(form)
        for key, alternatives in sorted(by_key.items()):
            code.append(f"    if key == {key} {{")
            for i in range(len(alternatives[0]["operands"])):
                code.append(f"        const p{i}: integer = list.get(list.get(flat, {i}), 1)")
            seen = set()
            for form in alternatives:
                conditions = []
                for i, operand in enumerate(form["operands"]):
                    if "literal" in operand:
                        conditions.append(f"p{i} == {operand['literal']}")
                    else:
                        if operand.get("min", 0) < 0 <= operand.get("max", -1):
                            conditions.append(f"(p{i} >= {operand['min']} || p{i} <= {operand['max']})")
                        else:
                            if "min" in operand:
                                conditions.append(f"p{i} >= {operand['min']}")
                            if "max" in operand:
                                conditions.append(f"p{i} <= {operand['max']}")
                        if operand.get("multiple", 1) != 1:
                            conditions.append(f"(p{i} % {operand['multiple']}) == 0")
                for constraint in form.get("constraints", []):
                    left, right = f"p{constraint['left']}", f"p{constraint['right']}"
                    conditions.append({"distinct": f"{left} != {right}",
                                       "base_distinct": f"({left} == 31 || {left} != {right})",
                                       "next": f"{left} == {right} + 1",
                                       "sum_max": f"{left} + {right} <= {constraint.get('max', 0)}"
                                       }[constraint["kind"]])
                expr = " | ".join([f"0x{form['base']:08x}"] +
                                  [f"({value_expr(form, f)} << {f['lsb']})" for f in form["fields"]])
                selector = " && ".join(conditions) or "true"
                if (selector, expr) in seen:
                    continue
                require(not any(s == selector for s, _ in seen), mnemonic,
                        "ambiguous syntax selector")
                seen.add((selector, expr))
                code += [f"        // {form['id']}: {form['encoding_id']}",
                         f"        if {selector} {{", f"            return {expr};", "        }"]
            code += [f'        assert(false, "a64 {mnemonic}: operand value out of range")',
                     "        return 0;", "    }"]
        code += [f'    assert(false, "a64 {mnemonic}: invalid operand classes or count")',
                 "    return 0;", "}",
                 f"fn a64_e5_{mnemonic}(args: list) {{",
                 f"    emit.u32(a64_e5_{mnemonic}_word(args))", "}",
                 f"fn a64_e5_{mnemonic}_shape(args: list) {{",
                 "    const key: u64 = a64_signature(a64_flatten(args))",
                 f'    assert({" || ".join(f"key == {key}" for key in sorted(by_key))}, '
                 f'"a64 {mnemonic}: invalid operand classes or count")', "}", ""]
    return "\n".join(code)


def render_macros(groups, mops_kinds):
    macros = ["// Generated statement macros for FEAT_MOPS/FEAT_CSSC.",
              "// Shared macro owners dispatch standard abs/cnt/smax/smin/umax/umin syntax;",
              "// this file retains cssc_ aliases for compatibility. Other E5 mnemonics use",
              "// their standard names.", ""]
    for mnemonic in sorted(groups):
        macro_name = f"cssc_{mnemonic}" if mnemonic in CSSC_SCALAR_CONFLICTS else mnemonic
        if mnemonic in mops_kinds:
            macros += [f"macro {macro_name}(...args) {{",
                       f'    const parsed: list = a64_mops_operands(args, "{mops_kinds[mnemonic]}")',
                       f"    a64_e5_{mnemonic}_shape(parsed)",
                       f"    a64_e5_{mnemonic}(parsed)", "}", ""]
        else:
            macros += [f"macro {macro_name}(...args) {{",
                       f'    a64_e5_{mnemonic}_shape(a64_operands(args, false, false, false, false, "{mnemonic}"))',
                       f'    a64_e5_{mnemonic}(a64_operands(args, false, false, true, false, "{mnemonic}"))',
                       "}", ""]
    return "\n".join(macros)


def render(data):
    validate_e5(data)
    groups = defaultdict(list)
    for form in data["forms"]:
        groups[form["mnemonic"]].append(form)
    mops_kinds = {}
    for form in data["forms"]:
        mnemonic = form["mnemonic"]
        kind = ("setgo" if mnemonic.startswith("setgo") else
                "set" if mnemonic.startswith("set") else
                "cpy" if mnemonic.startswith("cpy") else None)
        if kind is not None:
            require(mnemonic not in mops_kinds or mops_kinds[mnemonic] == kind,
                    mnemonic, "conflicting MOPS syntax class")
            mops_kinds[mnemonic] = kind

    code = render_word_functions(groups)
    macros = render_macros(groups, mops_kinds)
    artifacts = {
        "a64/generated/instructions-e5.inc": code.encode("ascii"),
        "a64/generated/instructions-e5-macros.inc": macros.encode("ascii"),
    }
    manifest = {k: data[k] for k in
                ("format_version", "batch", "source_lock", "planned_records", "forms",
                 "blocked_records", "alternatives", "xml_entries", "inventory_sha256",
                 "xml_sha256") if k in data}
    manifest.update({"generator": "a64-e5-finite-forms-v1",
                     "mapping_sha256": digest(canonical(data)),
                     "files": {name: digest(value) for name, value in artifacts.items()},
                     "macro_mnemonics": sorted(groups),
                     "mops_mnemonics": sorted(mops_kinds),
                     "cssc_prefixed_macros": sorted(CSSC_SCALAR_CONFLICTS & set(groups)),
                     "word_function_prefix": "a64_e5_"})
    artifacts["a64/generated/e5-manifest.json"] = canonical(manifest)
    return artifacts


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rules", type=Path, default=HERE / "rules/e5.json")
    parser.add_argument("--output", type=Path, default=ROOT / "include/arm")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads(args.rules.read_bytes())
    artifacts = render(data)
    for name, value in artifacts.items():
        path = args.output / name
        if args.check:
            require(path.is_file() and path.read_bytes() == value, name, "stale E5 artifact")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(value)
    n_forms = len(data["forms"])
    print(f"{'Checked' if args.check else 'Generated'} E5: {len(data['planned_records'])} records, "
          f"{n_forms} forms, {len({f['mnemonic'] for f in data['forms']})} API/macro pairs")


if __name__ == "__main__":
    main()
